### ISSUE TITLE
[Bug] Biome registration not working?

### ISSUE THREAD

**Issue by Ariannae** [primetoxinz/CoralReef#12]
On the most recent version for 1.12.2, it appears that only the Ocean biome works for coral reef generation. Even the default configuration file that contains deep ocean and beach fail to spawn coral reefs in these biomes.

**Comment by Ghostrider231** [comment]
Hello, i'm not the author but have you tried adding **deep_ocean** instead of **deep ocean**? (yes I've found this out the hard way. Any biome with a spaced name needs to have an underline)

Definitely works for me, and this also fixes the beach biome registration as well.

I did mention this in the mod's comment section but it appears to be disabled alongside with my correction on biome registration post.

**Comment by Ariannae** [comment]
Incredibly late response, but your suggestion definitely fixed it. Thank you so much Ghostrider!
